出现问题：signer1发送PrePrepare消息后，其他节点接收不到该消息，进而触发了viewChange事件。
```
> miner.start()
INFO [10-31|16:19:09] Transaction pool price threshold updated price=18000000000
INFO [10-31|16:19:09] Starting mining operation 
INFO [10-31|16:19:09] Commit new mining work                   number=1 txs=0 uncles=0 elapsed=122.172µs
null
> 2017/10/31 16:19:09 Replica 0 received a block 423b9ec1e0431be488cf7f1a9d10302aff950aac7a8ce2d3a9087f8adc4f17ce
2017/10/31 16:19:09 Replica 0 soft starting new view timer for 2s: new block 423b9ec1e0431be488cf7f1a9d10302aff950aac7a8ce2d3a9087f8adc4f17ce
2017/10/31 16:19:09 Replica 0 is primary, issuing pre-prepare for block 423b9ec1e0431be488cf7f1a9d10302aff950aac7a8ce2d3a9087f8adc4f17ce
2017/10/31 16:19:09 Primary 0 broadcasting pre-prepare for view=0/seqNo=9 and digest 423b9ec1e0431be488cf7f1a9d10302aff950aac7a8ce2d3a9087f8adc4f17ce
2017/10/31 16:19:09 Starting timer
2017/10/31 16:19:09 Replica 0 prepare count for view=0/seqNo=9: 0
2017/10/31 16:19:09 Attempting to stop an unfired idle timer
2017/10/31 16:19:09 Stopping timer
2017/10/31 16:19:11 Event timer fired
2017/10/31 16:19:11 Timer event delivered
2017/10/31 16:19:11 Replica 0 batch main thread looping
2017/10/31 16:19:11 Replica 0 processing event
2017/10/31 16:19:11 Replica 0 view change timer expired, sending view change: new block 423b9ec1e0431be488cf7f1a9d10302aff950aac7a8ce2d3a9087f8adc4f17ce
2017/10/31 16:19:11 Replica 0 stopping a running new view timer
2017/10/31 16:19:11 Replica 0 prepare count for view=0/seqNo=9: 0
2017/10/31 16:19:11 Attempting to stop an unfired idle timer
2017/10/31 16:19:11 Stopping timer
```
# 一、
* 出现错误的原因：在`func (pm *ProtocolManager) BroadcastMsg(msg *types.PbftMessage)`里加入输出语句，发现在执行`err := peer.SendMsg(msg)`时报错，返回的错误是`--err:=peer.SendMsg(msg)-- invalid message code: not handled`。函数`func (p *peer) SendMsg(msg *types.PbftMessage) error`经过层层调用，最终调用了`func (rw *protoRW) WriteMsg(msg Msg) (err error)`，在这个函数里面有一个判断
```
if msg.Code >= rw.Length {
		return newPeerError(errInvalidMsgCode, "not handled")
	}

```
`rw.Length`是结构体`Protocol`下的一个成员变量，该变量代表了`message code`的长度，也就是个数。由于我们在`eth/protocol.go`里面增加`ConsensusMsg`，所以这个`Length`也得变化。
* 解决方法：
`Protocol.Length`在`func NewProtocolManager(config *params.ChainConfig, mode downloader.SyncMode, networkId uint64, maxPeers int, mux *event.TypeMux, txpool txPool, engine consensus.Engine, blockchain *core.BlockChain, chaindb ethdb.Database) (*ProtocolManager, error)`里面通过`Length:  ProtocolLengths[i]`语句进行初始化，在`eth/protocol.go`里找到`var ProtocolLengths = []uint64{17, 8}`,它代表了不同协议版本执行消息的个数，把他变为`var ProtocolLengths = []uint64{18, 9}`,问题解决。
# 二、
解决完上述问题之后，`Preprepare`消息能成功传递到各个节点，但是在执行`handleMsg`时报错：
```
> admin.addPeer("enode://1ca0c0cd707d5eec374117ff925a91c5e0322d61b0f42be0a1a8e5ba2c85af19be7a41dfb3848865096b8149fa2c6d95a6cd7fcf31c898d0a8a0f3387e283d52@127.0.0.1:2000")
true
> ----msg := <-rw.in---
----msg := <-rw.in---
-----msg.Code is ------ 17
------err2 := pm.handleMsg(p)----- Invalid message - msg #17 (651 bytes): invalid message: (code 11) (size 651) rlp: type types.isPbftMessage_Payload is not RLP-serializable
```
* 解决问题的方法：
修改`pbftMessage`的格式为:
```
type PbftMessage struct {
	//Payload isPbftMessage_Payload `protobuf_oneof:"payload"`
	Payload isPbftMessagepayload ////--xiaobei 11.2
}
```
问题解决。（其实后来发现，问题并没有解决，rlp还是不能对`isPbftMessagepayload`进行编码）
# 三、
* 出现的问题：解决完上述问题后，signer2能从`manager.Queue()`里取出`PbftMessage`，并调用`func (instance *pbftCore) ProcessEvent(e events.Event) events.Event`进行处理，但是对`PbftMessage`的类型做出判断后，直接调用了default里的执行语句：
```
2017/11/02 20:19:14 Replica 1 received an unknown message type pbft.Pbftmessage
```
* 解决问题的方法：这是因为在`handleMsg()`时对ConsensusMsg进行处理的时候，忘记把`PbftMessage`的指针传过去，修改语句
```
pm.pbftmanager.Queue() <- &PbftMessage ////--xiaobei 11.2
```
# 四、
* 出现的问题：修改完这个后，`ProcessEvent()`能够在case语句中对`PbftMessage`进行处理，但是发现在处理`next, err := instance.recvMsg(msg.Msg, msg.Sender)`时进行报错,这是因为我们把`PbftMessage`放入`commChan`的时候，并没有把sender放进去。
* 解决方法：我在`protocolManager`调用`func (self *ProtocolManager) processConsensusMsg()`进行广播的时候，初始化了
```
msg2 := &pbft.Pbftmessage{ ////--xiaobei 11.2
			Sender: self.id,
			Msg:    msg1,
		}
		self.BroadcastMsg(msg2)
```
获得`replicaID`的方法是在`func NewProtocolManager(config *params.ChainConfig, mode downloader.SyncMode, networkId uint64, maxPeers int, mux *event.TypeMux, txpool txPool, engine consensus.Engine, blockchain *core.BlockChain, chaindb ethdb.Database) (*ProtocolManager, error)`里加入语句`manager.id = pb.GetReplicaID()`，从Pbft里获得。

这里注意不要忘了把`pbftMessage`变为`Pbftmessage`,因为首字母小写的话该结构体不能再外部包里调用。

# 五、
* 出现问题： 解决完上述问题后，又出现新问题：
```
2017/11/02 20:55:11 Replica 1 batch main thread looping
2017/11/02 20:55:11 Replica 1 processing event
2017/11/02 20:55:11 Replica 1 batch main thread looping
2017/11/02 20:55:11 Replica 1 processing event
2017/11/02 20:55:11 Replica 1 received incoming message from 0
proto: no encoder for Payload types.isPbftMessage_Payload [GetProperties]
proto: tag has too few fields: ""
```
发现在调用`p2p.Send(p.rw, ConsensusMsg, msg)`里对msg进行编码的时候，没有成功对`Pbftmessage`的成员变量`Payload`进行编码，`Payload`的类型是`types.isPbftMessage_Payload`，这是一个接口，rlp不能对接口进行编码？

* 解决问题的方法：
将原来的`Pbftmessage`和`PbftMessage`合并成了`PbftMessage`：
```
type PbftMessage struct {
	// Types that are valid to be assigned to Payload:
	// PrePrepare *PrePrepare //=> payload = 1
	// Prepare    *Prepare    //=> payload = 2
	// Commit     *Commit     //=> payload = 3
	// Checkpoint *Checkpoint //=> payload = 4
	// ViewChange *ViewChange //=> payload = 5
	// NewView    *NewView    //=> payload = 6
	Sender      uint64 //=>add. --Agzs
	PayloadCode uint64
	Payload     interface{}
}
const (
	// PbftMessage payload
	PrePrepareMsg    = 0x01
	PrepareMsg       = 0x02
	CommitMsg        = 0x03
	CheckpointMsg    = 0x04
	ViewChangeMsg    = 0x05
	NewViewMsg       = 0x06
	FetchBlockMsgMsg = 0x07
)
```
各种共识消息将继承`Payload`接口，在函数`func (pm *ProtocolManager) handleMsg(p *peer) error`里取消对`ConsensusMsg`的处理，改为对各种消息类型进行分别处理，处理完之后再统一封装成为`PbftMessage`类型放入`Queue()`里面。在调用`p2p.send()`之前也在`func (p *peer) SendMsg(msg *types.PbftMessage) error`里对共识消息进行分类处理，处理成明确的共识消息类型后再发送出去。


~根据在代码中加入输出语句，猜想出错原因如下：signer1发送`preprepare`消息后，signer2的protocalManager接收来自signer1的消息后，经过层层调用，最终调用`func (pm *ProtocolManager) handle(p *peer) error`时在执行以下步骤时会报错：~
```
if err := p.Handshake(pm.networkId, td, head, genesis); err != nil {
		p.Log().Debug("Ethereum handshake failed", "err", err)
		return err
	}
```
~这里就直接返回了，不会再后期调用`func (pm *ProtocolManager) handleMsg(p *peer) error `，也就无法对`ConsensusMsg`进行处理，进而不能把`pbftMessage`放入manager的`events`管道。~

~在握手协议时进行报错的根本原因在于，在调用`func (p *peer) Handshake(network uint64, td *big.Int, head common.Hash, genesis common.Hash) error`的内部执行了`errc <- p.readStatus(network, &status, genesis)`，进而调用了`func (p *peer) readStatus(network uint64, status *statusData, genesis common.Hash) (err error)`。在这个函数里面报错地方有两个，第一个就是`readMsg`报错，再一个就是`status.GenesisBlock != genesis`~